/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ResizableContainer {

    }
  }

  interface HTMLResizableContainerElement extends StencilComponents.ResizableContainer, HTMLStencilElement {}

  var HTMLResizableContainerElement: {
    prototype: HTMLResizableContainerElement;
    new (): HTMLResizableContainerElement;
  };
  interface HTMLElementTagNameMap {
    'resizable-container': HTMLResizableContainerElement;
  }
  interface ElementTagNameMap {
    'resizable-container': HTMLResizableContainerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'resizable-container': JSXElements.ResizableContainerAttributes;
    }
  }
  namespace JSXElements {
    export interface ResizableContainerAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface YearCounter {
      'since': number;
    }
  }

  interface HTMLYearCounterElement extends StencilComponents.YearCounter, HTMLStencilElement {}

  var HTMLYearCounterElement: {
    prototype: HTMLYearCounterElement;
    new (): HTMLYearCounterElement;
  };
  interface HTMLElementTagNameMap {
    'year-counter': HTMLYearCounterElement;
  }
  interface ElementTagNameMap {
    'year-counter': HTMLYearCounterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'year-counter': JSXElements.YearCounterAttributes;
    }
  }
  namespace JSXElements {
    export interface YearCounterAttributes extends HTMLAttributes {
      'since'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;